'''
Generated by Chat GPT
'''

def print_board(board):
    # Print the current state of the board
    for i in range(3):
        print(" " + board[i][0] + " | " + board[i][1] + " | " + board[i][2])
        if i != 2:
            print("---|---|---")

def get_move(board, player):
    # Prompt the player for their move and validate the input
    while True:
        move = input("Player " + player + ", enter your move (row, column): ")
        row, col = move.split(",")
        row = int(row) - 1
        col = int(col) - 1
        if row < 0 or row > 2 or col < 0 or col > 2:
            print("Invalid input. Please enter a valid row and column number (1-3).")
        elif board[row][col] != " ":
            print("That space is already taken. Please choose another.")
        else:
            return (row, col)

def check_win(board):
    # Check if a player has won the game
    for i in range(3):
        if board[i][0] == board[i][1] == board[i][2] != " ": # Check rows
            return board[i][0]
        elif board[0][i] == board[1][i] == board[2][i] != " ": # Check columns
            return board[0][i]
    if board[0][0] == board[1][1] == board[2][2] != " ": # Check diagonals
        return board[0][0]
    elif board[0][2] == board[1][1] == board[2][0] != " ":
        return board[0][2]
    else:
        return None

def play_game():
    # Initialize the board and player turn
    board = [[" ", " ", " "], [" ", " ", " "], [" ", " ", " "]]
    player = "X"
    
    # Loop until the game is over
    while True:
        print_board(board)
        move = get_move(board, player)
        row, col = move
        board[row][col] = player
        winner = check_win(board)
        if winner:
            print_board(board)
            print("Congratulations, player " + player + " wins!")
            return
        elif all(" " not in row for row in board):
            print_board(board)
            print("The game is a tie.")
            return
        else:
            player = "O" if player == "X" else "X"

# Start the game
play_game()
